// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH8tRR7KJ12S00vMlac9LbZ7Zbv0O5ECA',
    appId: '1:676447781469:web:c5cdcc1b064f186d3443b4',
    messagingSenderId: '676447781469',
    projectId: 'parking-app-2859f',
    authDomain: 'parking-app-2859f.firebaseapp.com',
    storageBucket: 'parking-app-2859f.firebasestorage.app',
    measurementId: 'G-8TRZVZ516W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIL0gy5uX22AJESIcPRLaoBA_I9jQUE08',
    appId: '1:676447781469:android:6bca3ff603c2653e3443b4',
    messagingSenderId: '676447781469',
    projectId: 'parking-app-2859f',
    storageBucket: 'parking-app-2859f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8KX_OULD73sm3JeB6HFagETVZGw7kJMg',
    appId: '1:676447781469:ios:44996a0edfb6478c3443b4',
    messagingSenderId: '676447781469',
    projectId: 'parking-app-2859f',
    storageBucket: 'parking-app-2859f.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8KX_OULD73sm3JeB6HFagETVZGw7kJMg',
    appId: '1:676447781469:ios:44996a0edfb6478c3443b4',
    messagingSenderId: '676447781469',
    projectId: 'parking-app-2859f',
    storageBucket: 'parking-app-2859f.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );
}
